### ISSUE TITLE
error occured when rake task of active_record:sharding:sequencer:setup executing, if using gem "activerecord-import"

### ISSUE THREAD

**Issue by ukayare** [hirocaster/activerecord-sharding#10]
error is follow

```
$ bundle exec rake  active_record:sharding:sequencer:setup
user_sequencer_development already exists
rake aborted!
NoMethodError: undefined method `connection' for #<Array:0x007fec80a13af0>
/xxx/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/active_record/sharding/database_tasks.rb:162:in `execute'
/xxx/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/active_record/sharding/database_tasks.rb:195:in `create_table_sequencer_database'
/xxx/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/tasks/activerecord-sharding.rake:55:in `block (4 levels) in <top (required)>'
/xxx/vendor/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/active_record/sharding/database_tasks.rb:100:in `invoke_task_for_sequencer'
/xxx/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/active_record/sharding/database_tasks.rb:94:in `block in invoke_task_for_all_sequencers'
/xxx/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/active_record/sharding/database_tasks.rb:93:in `each'
/xxx/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/active_record/sharding/database_tasks.rb:93:in `invoke_task_for_all_sequencers'
/xxx/bundle/ruby/2.2.0/gems/activerecord-sharding-0.1.0/lib/tasks/activerecord-sharding.rake:74:in `block (4 levels) in <top (required)>'
Tasks: TOP => active_record:sharding:sequencer:create_table
(See full trace by running task with --trace)
```

this error line (https://github.com/hirocaster/activerecord-sharding/blob/master/lib/active_record/sharding/database_tasks.rb#L162) puts of `ActiveRecord::Base.establish_connection(configuration)`

```
[[#<Proc:0x007fbd2cbf6120@/xxx/bundle/ruby/2.2.0/gems/activerecord-import-0.8.0/lib/activerecord-import.rb:11>, {}]]
```

dependency of activerecord-import gem discovered.

**Comment by hirocaster** [comment]
I guess cause switched object by activerecord-import
